# Generated by Django 2.1.15 on 2022-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Department_ID', models.IntegerField()),
                ('Departments', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('EnRoll_ID', models.IntegerField()),
                ('Department_Name', models.CharField(max_length=150)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=30)),
                ('Date_Of_Joining', models.DateField()),
                ('Address', models.CharField(max_length=200)),
                ('Photo_Name', models.ImageField(blank=True, upload_to='images')),
                ('Documents_Name', models.FileField(blank=True, upload_to='documents')),
            ],
        ),
    ]
